version: "3"

services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        deploy:
            resources:
                limits:
                    memory: 256M
        ports:
            - ${APP_PORT}:80
        image: app-image
        container_name: laravel-app
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    db:
        deploy:
            resources:
                limits:
                    memory: 512M
        image: mariadb
        container_name: laravel-db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: "${DB_HOST}"
            PMA_USER: "${DB_USERNAME}"
            PMA_PASSWORD: "${DB_PASSWORD}"
        ports:
            - 8080:80
        volumes:
            - ./infra/docker/phpmyadmin/sessions:/sessions
        depends_on:
            - db
